# Generated by Django 4.2.5 on 2023-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='users/')),
            ],
        ),
    ]
