# Generated by Django 4.2.5 on 2023-09-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='users/'),
        ),
    ]
