# Generated by Django 4.2.5 on 2023-09-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_skills_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='class_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
