# Generated by Django 4.2.5 on 2023-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='class_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
