# Generated by Django 4.2.5 on 2023-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_languages_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
            ],
        ),
    ]
