# Generated by Django 4.2.5 on 2023-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_workexperince'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperince',
            name='company_link',
            field=models.CharField(default='', max_length=128),
        ),
    ]
