# Generated by Django 4.2.5 on 2023-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_workexperince_company_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperince',
            name='date_time',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
