# Generated by Django 4.2.5 on 2023-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_workexperince_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperince',
            name='about',
            field=models.CharField(default='', max_length=128),
        ),
    ]
