# Generated by Django 4.2.5 on 2023-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_workexperince_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=52)),
                ('education_link', models.CharField(default='', max_length=128)),
                ('date_time', models.CharField(max_length=52)),
                ('about', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='workexperince',
            name='about',
            field=models.CharField(default='', max_length=512),
        ),
    ]
