# Generated by Django 4.2.5 on 2023-09-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_educations_alter_workexperince_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icons', models.CharField(max_length=128)),
                ('social_icons_link', models.CharField(max_length=128)),
                ('powered_by', models.CharField(max_length=128)),
                ('hashtags', models.TextField()),
            ],
        ),
    ]
