# Generated by Django 4.2.5 on 2023-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='powered_by',
            new_name='company',
        ),
        migrations.AddField(
            model_name='footer',
            name='company_link',
            field=models.CharField(default='', max_length=128),
        ),
    ]
